[build]
builder = "NIXPACKS"
buildCommand = "apt-get update && apt-get install -y python3 make g++ && npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE" 