[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[build.env]
NODE_VERSION = "20.18.0"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
NPM_CONFIG_ENGINE_STRICT = "false" 